tripin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tripin.DAL;

namespace tripin.Controllers
{
    public class HomeController : Controller
    {
        private TripinDbContext db = new TripinDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViladoConde()
        {
            return View();
        }

        public ActionResult PovoadeVarzim()
        {
            //Buscar Pontos de Póvoa de Varzim
            var pontos = from m in db.Pontos.Where(p => p.localidade == "Póvoa de Varzim")
                         select m;

            return View(pontos);
        }

        public ActionResult VisitaVirtual()
        {
            return View();
        }
    }
}

tripin/Controllers/RotasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tripin.DAL;
using tripin.Models;

namespace tripin.Controllers
{
    public class RotasController : Controller
    {
        private TripinDbContext db = new TripinDbContext();

        // GET: Rotas
        public ActionResult Index()
        {
            return View(db.Rotas.ToList());
        }

        // GET: Rotas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rota rota = db.Rotas.Find(id);
            if (rota == null)
            {
                return HttpNotFound();
            }
            return View(rota);
        }

        // GET: Rotas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rotas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RotaID,nome_rota,lat1_rota,lat2_rota,lat3_rota,lat4_rota,lat5_rota,lon1_rota,lon2_rota,lon3_rota,lon4_rota,lon5_rota")] Rota rota)
        {
            if (ModelState.IsValid)
            {
                db.Rotas.Add(rota);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rota);
        }

        // GET: Rotas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rota rota = db.Rotas.Find(id);
            if (rota == null)
            {
                return HttpNotFound();
            }
            return View(rota);
        }

        // POST: Rotas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RotaID,nome_rota,lat1_rota,lat2_rota,lat3_rota,lat4_rota,lat5_rota,lon1_rota,lon2_rota,lon3_rota,lon4_rota,lon5_rota")] Rota rota)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rota).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rota);
        }

        // GET: Rotas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rota rota = db.Rotas.Find(id);
            if (rota == null)
            {
                return HttpNotFound();
            }
            return View(rota);
        }

        // POST: Rotas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rota rota = db.Rotas.Find(id);
            db.Rotas.Remove(rota);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tripin/Views/Home/Index.cshtml

@{
    ViewBag.Title = "TripIn";
}
<br /><br />
<style>
    span {
        color: #18BC9C;
    }

    h2 {
        color: #18BC9C;
    }
</style>
<h1 align="center">Trip<span>In</span></h1>
<h6 align="center"><i>Lema</i></h6>
<br />
@*//Carousel*@
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="@Url.Content("~/Content/assets/")vila.jpg" alt="Chania">
        </div>

        <div class="item">
            <img src="@Url.Content("~/Content/assets/")vila.jpg" alt="Chania">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<br /><br /><br />
<h2 class="section-title" align="center">
    Principais Locais a Visitar
</h2>
<br /><br /><br />
<div class="col-sm-4">
    <img src="@Url.Content("~/Content/assets/")praia.jpg" alt="visit-image" class="img-responsive visit-item" onmouseover="this.src='@Url.Content("~/Content/assets/")praia2.png';" onmouseout="this.src='@Url.Content("~/Content/assets/")praia.jpg';">
</div>
<div class="col-sm-4">
    <img src="@Url.Content("~/Content/assets/")casino.jpg" alt="visit-image" class="img-responsive visit-item">
</div>
<div class="col-sm-4">
    <img src="@Url.Content("~/Content/assets/")ruadajunqueira.jpg" alt="visit-image" class="img-responsive visit-item">
</div>

<br /><br /><br />





tripin/Views/Home/PovoadeVarzim.cshtml
@model IEnumerable<tripin.Models.Ponto>
@{
    ViewBag.Title = "Póvoa de Varzim";
    var queryCordAloj = "SELECT latitude_ponto, longitude_ponto FROM Ponto WHERE tipo_ponto like 'alojamento'";
    var queryCordBar = "SELECT latitude_ponto, longitude_ponto FROM Ponto WHERE tipo_ponto like 'bar'";
}
<style>
    h2, h4 {
        color: #18BC9C;
    }

    p#rel:hover {
        color: darkorange;
    }

    p#atl:hover {
        color: #80e0d0;
    }

    p#cit:hover {
        color: #dc143c;
    }

    p#cul:hover {
        color: #32cd32;
    }
</style>

<br /><br />
<h2>@ViewBag.Title.</h2>

<i>"É tão bom viver aqui!"</i>
<br /><br /><br /><br />
<div class="col-sm-6">
    <div id="map" style="width:550px;height:470px;"></div>
    <script type="text/javascript">
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: { lat: 41.3797279, lng: -8.7582672 },
                zoom: 14
            });
        }

        function marker(tipo) {
            if (tipo == "alojamento")
            {
                var img = "@Url.Content("~/Content/assets/")markers/alojamento.png";

                var marker = new google.maps.Marker({
                    //falta ir buscar a latitude e longitude de acordo com o tipo de ponto
                    position: { lat: 41.378564, lng: -8.766137 },
                    map: map,
                    icon: img
                });

                // put in some information about each json object - in this case, the opening hours.
                //var infowindow = new google.maps.InfoWindow({
                //  content: "<div class='infoDiv'><h2>" + item.NomeLocal + "</h2>" + item.Descricao + "<br />" + item.Url + "</div></div>"
                //});

                // finally hook up an "OnClick" listener to the map so it pops up out info-window when the marker-pin is clicked!
                //google.maps.event.addListener(marker, 'click', function () {
                //  infowindow.open(map, marker);
                //});
            }

            if (tipo == "bar")
            {
                var img = "@Url.Content("~/Content/assets/")markers/bar.png";

                var marker = new google.maps.Marker({
                    //falta ir buscar a latitude e longitude de acordo com o tipo de ponto
                    position: { lat: 41.385647, lng: -8.772484 },
                    map: map,
                    icon: img
                });
            }
        }

            function rota(nome)
            {
                if(nome == "atl")
                {
                    var rota = [
                  { lat: 41.378564, lng: -8.766137 },
                  { lat: 41.387005, lng: -8.770477 },
                  { lat: 41.37813, lng: -8.7602697 }
                ];
                var rota1 = new google.maps.Polyline({
                    path: rota,
                    strokeColor: '#80e0d0',
                    strokeOpacity: 1.0,
                    strokeWeight: 2
                });
                rota1.setMap(map);
                }
                if (nome == "cit") {
                    var rota = [
                  { lat: 41.378564, lng: -8.766137 },
                  { lat: 41.387005, lng: -8.770477 },
                  { lat: 41.37813, lng: -8.7602697 }
                    ];
                    var rota1 = new google.maps.Polyline({
                        path: rota,
                        strokeColor: '#dc143c',
                        strokeOpacity: 1.0,
                        strokeWeight: 2
                    });
                    rota1.setMap(map);
                }
                if (nome == "cul") {
                    var rota = [
                  { lat: 41.378564, lng: -8.766137 },
                  { lat: 41.387005, lng: -8.770477 },
                  { lat: 41.37813, lng: -8.7602697 }
                    ];
                    var rota1 = new google.maps.Polyline({
                        path: rota,
                        strokeColor: '#32cd32',
                        strokeOpacity: 1.0,
                        strokeWeight: 2
                    });
                    rota1.setMap(map);
                }
                if (nome == "rel") {
                    var rota = [
                  { lat: 41.378564, lng: -8.766137 },
                  { lat: 41.387005, lng: -8.770477 },
                  { lat: 41.37813, lng: -8.7602697 }
                    ];
                    var rota1 = new google.maps.Polyline({
                        path: rota,
                        strokeColor: 'darkorange',
                        strokeOpacity: 1.0,
                        strokeWeight: 2
                    });
                    rota1.setMap(map);
                }

            }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDo58rJU3nGrM0-KZHhXIcPV_Kwu5HnsU0&callback=initMap" async defer></script> 
</div>



<div class="col-sm-3">
    <h4>Pontos de Interesse</h4>
    <br>
    <p onclick="marker('alojamento')"><img src="@Url.Content("~/Content/assets/")markers/alojamento.png" alt="">Alojamento</p>
    <p onclick="marker('bar')"><img src="@Url.Content("~/Content/assets/")markers/bar.png" alt="">Lazer</p>
    <p onclick="marker('igreja')"><img src="@Url.Content("~/Content/assets/")markers/igreja.png" alt="">Igrejas</p>
    <p onclick="marker('info')"><img src="@Url.Content("~/Content/assets/")markers/info.png" alt="">Informações</p>
    <p onclick="marker('monumentos')"><img src="@Url.Content("~/Content/assets/")markers/monumentos.png" alt="">Monumentos</p>
    <p onclick="marker('museu')"><img src="@Url.Content("~/Content/assets/")markers/museu.png" alt="">Museus</p>
    <p onclick="marker('praia')"><img src="@Url.Content("~/Content/assets/")markers/praia.png" alt="">Praia</p>
    <p onclick="marker('restaurantes')"><img src="@Url.Content("~/Content/assets/")markers/restaurantes.png" alt="">Restaurantes</p>

</div>
<div class="col-sm-3">
    <h4>Rotas</h4>
    <br>
    <p id="atl" onclick="rota('atl')">Rota Atlântica</p>
    <br>
    <p id="cit" onclick="rota('cit')">Rota Citadina</p>
    <br>
    <p id="cul" onclick="rota('cul')">Rota Cultural</p>
    <br>
    <p id="rel" onclick="rota('rel')">Rota Religiosa</p>
    <br>
    <p>@Html.ActionLink("Criar Nova", "Create", "Rotas")</p>
</div>

tripin/Views/Home/ViladoConde.cshtml
@{
    ViewBag.Title = "Vila do Conde";
}
<style>
    h2, h4 {
        color: #18BC9C;
    }

    p#rel:hover {
        color: darkorange;
    }

    p#atl:hover {
        color: #80e0d0;
    }

    p#cit:hover {
        color: #dc143c;
    }

    p#cul:hover {
        color: #32cd32;
    }
</style>
<br /><br />
<h2>@ViewBag.Title</h2>
<i>"O lugar onde o coração se escondee e a mulher eterna tsem luz na fronte fica no norte e é Vila do Conde" - Ruy Belo</i>
<br /><br /><br /><br />
<div class="col-sm-6">
    <div id="map" style="width:550px;height:470px;"></div>
    <script>
					var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 41.3507, lng: -8.7474079},
          zoom: 14
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDo58rJU3nGrM0-KZHhXIcPV_Kwu5HnsU0&callback=initMap" async defer></script> 
</div>



<div class="col-sm-3">
    <h4>Pontos de Interesse</h4>
    <br>
    <p><img src="@Url.Content("~/Content/assets/")markers/alojamento.png" alt="">Alojamento</p>
    <p><img src="@Url.Content("~/Content/assets/")markers/bar.png" alt="">Bares</p>
    <p><img src="@Url.Content("~/Content/assets/")markers/igreja.png" alt="">Igrejas</p>
    <p><img src="@Url.Content("~/Content/assets/")markers/info.png" alt="">Informações</p>
    <p><img src="@Url.Content("~/Content/assets/")markers/monumentos.png" alt="">Monumentos</p>
    <p><img src="@Url.Content("~/Content/assets/")markers/museu.png" alt="">Museus</p>
    <p><img src="@Url.Content("~/Content/assets/")markers/praia.png" alt="">Praia</p>
    <p><img src="@Url.Content("~/Content/assets/")markers/restaurantes.png" alt="">Restaurantes</p>

</div>
<div class="col-sm-3">
    <h4>Rotas</h4>
    <br>
    <p id="atl">Rota Atlântica</p>
    <br>
    <p id="cit">Rota Citadina</p>
    <br>
    <p id="cul">Rota Cultural</p>
    <br>
    <p id="rel">Rota Religiosa</p>
    <br>
    <a href="#">Criar Nova Rota</a>
</div>
<!-- /.row -->

tripin/Views/Home/VisitaVirtual.cshtml

@{
    ViewBag.Title = "VisitaVirtual";
}

<h2>VisitaVirtual</h2>
